language: node_js

node_js:
    - "8"
    - "10"
    - "11"
    - "node"

sudo: false

install:
    - "npm install"

before_script:
    - redis-server &
    - redis-server --unixsocket /tmp/redis.sock &
    - sleep 2
